/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Đăng ký theo dõi thiết bị Apple.
 *
 * Cách dùng phía Node.js:
 * ```js
 * onAppleDeviceEvent((event) => {
 *   // event.type: "connected" | "disconnected" | "trusted"
 *   // event.udid luôn có; event.info chỉ có khi type === "trusted"
 * });
 * ```
 */
export interface AppleDeviceEvent {
  eventType: string
  udid: string
  info?: AppleDeviceFullInfo
}

export interface AppleDeviceFullInfo {
  udid: string
  deviceName: string
  productType: string
  productVersion: string
  buildVersion: string
  serialNumber: string
  /**
   * Toàn bộ giá trị lockdown lấy được (GetAllValues), serialize sang JSON string
   * để không phải map cứng từng field một — phía Node có thể JSON.parse().
   */
  rawJson: string
}

/**
 * Copy file(s)/thư mục từ `from` (string hoặc string[]) sang `to`.
 * Trả về `id` ngay lập tức; theo dõi qua `onTransferProgress` / `onTransferResult`.
 */
export declare function copyFiles(from: string | Array<string>, to: string): string

/**
 * Bắt đầu tính hash cho `file_path` theo `options.sum`, so khớp với `options.value`.
 * Trả về ngay một `id` — job chạy nền, kết quả/progress đến qua các callback đã đăng ký.
 */
export declare function createHash(filePath: string, options: HashOptions): string

export interface DiskInfo {
  id: string
  name: string
  mountPoint: string
  busType: string
  filesystem: string
  totalSpace: number
  freeSpace: number
  usedSpace: number
  temperature: number
  isRemovable: boolean
  isReadonly: boolean
  diskType: DiskType
}

export declare const enum DiskType {
  Hdd = 'Hdd',
  Ssd = 'Ssd',
  Unknown = 'Unknown'
}

/** Trả về danh sách toàn bộ ổ đĩa hiện có trên hệ thống. */
export declare function getAllDisk(): Array<DiskInfo>

/**
 * Lấy thông tin chi tiết ổ đĩa chứa `path` (tự động resolve về root/mount point).
 * Trả về `null` nếu không tìm thấy ổ đĩa thay vì throw lỗi — phía JS tự check.
 */
export declare function getDiskInfo(path: string): DiskInfo | null

export interface HashOptions {
  /** "md5" | "sha1" | "sha256" */
  sum: string
  /**
   * Giá trị hash kỳ vọng để so khớp. Để rỗng ("") nếu chỉ muốn tính hash
   * mà không cần so khớp — khi đó `matched` trong kết quả luôn là false.
   */
  value: string
}

export interface HashProgress {
  id: string
  bytesProcessed: number
  totalBytes: number
  percent: number
  speedBps: number
  /** -1 nếu chưa tính được (tốc độ tức thời bằng 0) */
  etaSeconds: number
}

export interface HashResult {
  id: string
  sum: string
  computed: string
  expected: string
  matched: boolean
  error?: string
}

/**
 * Move file(s)/thư mục từ `from` (string hoặc string[]) sang `to`.
 * Trả về `id` ngay lập tức; theo dõi qua `onTransferProgress` / `onTransferResult`.
 */
export declare function moveFiles(from: string | Array<string>, to: string): string

export declare function onAppleDeviceEvent(callback: (event: AppleDeviceEvent) => void): void

/** Đăng ký callback nhận progress khi tính hash. Gọi 1 lần khi app khởi động. */
export declare function onHashProgress(callback: (progress: HashProgress) => void): void

/** Đăng ký callback nhận kết quả cuối cùng khi tính hash xong. */
export declare function onHashResult(callback: (result: HashResult) => void): void

/** Đăng ký callback nhận progress khi copy/move. */
export declare function onTransferProgress(callback: (progress: TransferProgress) => void): void

/** Đăng ký callback nhận kết quả cuối cùng khi copy/move xong. */
export declare function onTransferResult(callback: (result: TransferResult) => void): void

/**
 * Đăng ký callback theo dõi sự kiện USB cắm/rút.
 *
 * Cách dùng phía Node.js:
 * ```js
 * onUSBChanged((event) => {
 *   // event.eventType: "connected" | "disconnected"
 *   // event.disk: UsbDisk
 *   console.log(event.eventType, event.disk);
 * });
 * ```
 *
 * Việc theo dõi chạy trên một background thread poll mỗi 1.5s và diff danh
 * sách thiết bị — đủ nhanh cho UI mà không cần message loop riêng.
 */
export declare function onUsbChanged(callback: (event: UsbChangedEvent) => void): void

export interface TransferProgress {
  id: string
  currentFile: string
  filesDone: number
  totalFiles: number
  bytesDone: number
  totalBytes: number
  percent: number
  speedBps: number
  etaSeconds: number
}

export interface TransferResult {
  id: string
  success: boolean
  error?: string
  filesTransferred: number
  bytesTransferred: number
}

export interface UsbChangedEvent {
  eventType: string
  disk: UsbDisk
}

export interface UsbDisk {
  vendorId: number
  productId: number
  manufacturer: string
  productName: string
}
