/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cancelHash(id: string): void

export declare function cancelTransfer(id: string): void

export declare function copyFile(filePath: string, toFolder: string): string

export declare function createHash(filePath: string, hashType: HashType): string

export interface DiskInfo {
  id: string
  name: string
  mountPoint: string
  busType: string
  filesystem: string
  totalSpace: number
  freeSpace: number
  usedSpace: number
  temperature?: number
  isRemovable: boolean
  isReadonly: boolean
  diskType: DiskType
}

export declare const enum DiskType {
  HDD = 0,
  SSD = 1,
  NVME = 2,
  USB = 3,
  UNKNOWN = 4
}

export declare const enum Event {
  Progress = 0,
  Completed = 1,
  Error = 2,
  Canceled = 3,
  Pause = 4,
  Resume = 5
}

export declare function getAllDisk(): Array<DiskInfo>

export declare function getDiskInfo(path: string): DiskInfo | null

export interface HashEvent {
  id: string
  progress: number
  speed: number
  eta: number
  hash?: string
}

export declare const enum HashType {
  Md5 = 0,
  Sha1 = 1,
  Sha256 = 2
}

export declare function moveFile(from: string, to: string): string

export declare function onHashEvent(callback: (arg: string) => void): void

export declare function onTransferEvent(callback: (arg: string) => void): void

export declare function pauseHash(id: string): void

export declare function pauseTransfer(id: string): void

export declare function resumeHash(id: string): void

export declare function resumeTransfer(id: string): void

export interface TransferEvent {
  id: string
  event: Event
  progress?: number
  transferredBytes?: number
  totalBytes?: number
  speed?: number
  eta?: number
  error?: string
}
