// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Return the current app version from Cargo.toml.
	 *  Maps to `ElectronApi.getVersion`.
	 */
	getVersion: () => __TAURI_INVOKE<string>("get_version"),
	/**
	 *  Format a byte count into a human-readable string (e.g. "1.23 GB").
	 *  Maps to `ElectronApi.formatBytes`.
	 */
	formatBytes: (bytes: number | null, decimals: number | null) => __TAURI_INVOKE<string>("format_bytes", { bytes, decimals }),
	/**
	 *  Restart the application process.
	 *  Maps to `ElectronApi.relaunch`.
	 */
	relaunch: () => typedError<null, string>(__TAURI_INVOKE("relaunch")),
	/**
	 *  Send a toast / notification message to the frontend.
	 *  The frontend should `listen("app:message", ...)`.
	 *  Maps to `ElectronApi.onMessage` (emit side).
	 */
	sendMessage: (message: string, messageType: string) => typedError<null, string>(__TAURI_INVOKE("send_message", { message, messageType })),
	getFreeSpace: (path: string) => typedError<FreeSpaceResult, string>(__TAURI_INVOKE("get_free_space", { path })),
	getDriveInfo: (path: string) => typedError<DriveInfo, string>(__TAURI_INVOKE("get_drive_info", { path })),
	listDrives: () => __TAURI_INVOKE<string[]>("list_drives"),
	listDrivesInfo: () => typedError<DriveInfo[], string>(__TAURI_INVOKE("list_drives_info")),
	getBestDrive: (options: BestDriveOptions) => typedError<DriveInfo, string>(__TAURI_INVOKE("get_best_drive", { options })),
	getEnvironmentInfo: (path: string) => typedError<EnvInfo, string>(__TAURI_INVOKE("get_environment_info", { path })),
	/**
	 *  Return all tracked `.ipsw` files in the watched directory.
	 *  Maps to `ElectronApi.file.getFiles`.
	 */
	getFiles: () => typedError<IPSWFile[], string>(__TAURI_INVOKE("get_files")),
	/**
	 *  Delete one or more `.ipsw` files from disk *and* the tracked list.
	 *  Accepts an array of absolute file paths.
	 *  Maps to `ElectronApi.file.delete`.
	 */
	deleteFiles: (targets: string[]) => typedError<null, string>(__TAURI_INVOKE("delete_files", { targets })),
	/**
	 *  Switch the watched directory. Stops the old watcher, scans the new directory,
	 *  starts a fresh watcher, and emits the updated file list on `ipsw:reload`.
	 *  Maps to `ElectronApi.file.changeDir`.
	 */
	changeDir: (newDir: string) => typedError<null, string>(__TAURI_INVOKE("change_dir", { newDir })),
	/**
	 *  Get a filtered (or full) list of known devices.
	 *  Maps to `ElectronApi.getDevices`.
	 */
	getDevices: (product: "iphone" | "ipad" | "watch" | "mac" | "realitydevice" | "tv" | "homepod" | "ipod" | null) => typedError<BaseDevice[], string>(__TAURI_INVOKE("get_devices", { product })),
	/**
	 *  Fetch full model data (firmwares, boards, etc.) for a device identifier.
	 *  Returns `ModelDataResult::Wait` if the data isn't cached yet — the frontend
	 *  should listen on `dh:modelData` for the async response.
	 *  Maps to `ElectronApi.getModelData`.
	 */
	getModelData: (identifier: string) => typedError<ModelDataResult_Serialize, string>(__TAURI_INVOKE("get_model_data", { identifier })),
	/**
	 *  Check if model data is available locally, returning immediately.
	 *  Returns `ModelDataResult::Ready` if cached data exists, or `Wait` otherwise.
	 *  Maps to `ElectronApi.getDeviceModelData`.
	 */
	getDeviceModelData: (identifier: string) => typedError<ModelDataResult_Serialize, string>(__TAURI_INVOKE("get_device_model_data", { identifier })),
	/**
	 *  Trigger an async model-data fetch for the given identifier.
	 *  The result arrives later on the `dh:modelData` event channel.
	 *  Maps to `ElectronApi.requestModelData`.
	 */
	requestModelData: (identifier: string) => typedError<null, string>(__TAURI_INVOKE("request_model_data", { identifier })),
	/**
	 *  Set a value in the persistent store by key.
	 *  Maps to `ElectronStoreApi.set`.
	 */
	storeSet: (key: string, value: any) => typedError<null, string>(__TAURI_INVOKE("store_set", { key, value })),
	/**
	 *  Get a value from the persistent store by key.
	 *  Returns `null` when the key does not exist.
	 *  Maps to `ElectronStoreApi.get`.
	 */
	storeGet: (key: string) => typedError<any, string>(__TAURI_INVOKE("store_get", { key })),
	/**
	 *  Check whether a key exists in the persistent store.
	 *  Maps to `ElectronStoreApi.has`.
	 */
	storeHas: (key: string) => typedError<boolean, string>(__TAURI_INVOKE("store_has", { key })),
	/**
	 *  Delete a key from the persistent store.
	 *  Maps to `ElectronStoreApi.delete`.
	 */
	storeDelete: (key: string) => typedError<null, string>(__TAURI_INVOKE("store_delete", { key })),
	/**
	 *  Open a folder in the native file explorer by its path.
	 *  Maps to `ElectronApi.system.openFolder`.
	 */
	openFolder: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_folder", { path })),
	/**
	 *  Open a native dialog to pick a folder, returning the selected path.
	 *  Maps to `ElectronApi.system.pickFolder`.
	 */
	pickFolder: () => typedError<string | null, string>(__TAURI_INVOKE("pick_folder")),
	/**
	 *  Open a native dialog to pick a file, optionally filtered by extension.
	 *  Returns the full path of the selected file.
	 *  Maps to `ElectronApi.system.pickFile`.
	 */
	pickFile: (filterName: string | null, filterExt: string[] | null) => typedError<string | null, string>(__TAURI_INVOKE("pick_file", { filterName, filterExt })),
	/**
	 *  Run a shell command and return its stdout output.
	 *  Maps to `ElectronApi.system.runBinding`.
	 */
	runBinding: (command: string) => typedError<string, string>(__TAURI_INVOKE("run_binding", { command })),
	/**
	 *  Return the current update status.
	 *  This is a **stub** — a real implementation would integrate `tauri-plugin-updater`.
	 *  Maps to `ElectronUpdaterApi.getStatus`.
	 */
	getUpdateStatus: () => __TAURI_INVOKE<UpdateStatus>("get_update_status"),
	dmAdd: (firmware: Firmware, savePath: string) => typedError<AddResult_Serialize, string>(__TAURI_INVOKE("dm_add", { firmware, savePath })),
	dmPause: (id: string) => typedError<LifecycleResult_Serialize, string>(__TAURI_INVOKE("dm_pause", { id })),
	dmResume: (id: string) => typedError<LifecycleResult_Serialize, string>(__TAURI_INVOKE("dm_resume", { id })),
	dmCancel: (id: string) => typedError<LifecycleResult_Serialize, string>(__TAURI_INVOKE("dm_cancel", { id })),
	dmGetAllTasks: () => typedError<Task[], string>(__TAURI_INVOKE("dm_get_all_tasks")),
	dmGetIncompleteTasks: () => typedError<IncompleteTask[], string>(__TAURI_INVOKE("dm_get_incomplete_tasks")),
	dmResumeIncomplete: (id: string) => typedError<LifecycleResult_Serialize, string>(__TAURI_INVOKE("dm_resume_incomplete", { id })),
	dmDeleteIncomplete: (id: string) => typedError<LifecycleResult_Serialize, string>(__TAURI_INVOKE("dm_delete_incomplete", { id })),
	dmGetEnvironmentInfo: (savePath: string) => typedError<DiskEnvironmentInfo, string>(__TAURI_INVOKE("dm_get_environment_info", { savePath })),
	dmSetBoost: (enabled: boolean) => __TAURI_INVOKE<void>("dm_set_boost", { enabled }),
};

/* Types */
export type AddError = { error: "DiskFull" } | { error: "AlreadyInList" } | { error: "InvalidUrl" } | { error: "InvalidSavePath" } | { error: "UnknownDiskSpace" } | { error: "Unknown" };

export type AddResult = AddResult_Serialize | AddResult_Deserialize;

export type AddResult_Deserialize = {
	success: boolean,
	id: string | null,
	error: AddError | null,
};

export type AddResult_Serialize = {
	success: boolean,
	id?: string | null,
	error?: AddError | null,
};

export type BaseDevice = {
	name: string,
	identifier: string,
};

export type BaseFirmware = BaseFirmware_Serialize | BaseFirmware_Deserialize;

export type BaseFirmware_Deserialize = {
	identifier: string,
	buildid: string,
	version: string,
	url: string,
	filesize: number,
	releasedate: string,
	uploaddate: string,
	signed: boolean,
};

export type BaseFirmware_Serialize = {
	identifier: string,
	buildid: string,
	version: string,
	url: string,
	filesize: number,
	releasedate: string,
	uploaddate: string,
	signed: boolean,
};

/**  Options để lấy ổ tốt nhất */
export type BestDriveOptions = {
	/**  Dung lượng file cần lưu (bytes). None = bỏ qua filter size. */
	file_size: number,
	/**  Thư mục lưu file đang được cấu hình. */
	save_dir: string | null,
};

export type Board = Board_Serialize | Board_Deserialize;

export type Board_Deserialize = {
	bdid: number,
	boardconfig: string,
	cpid: number,
	platform: string,
};

export type Board_Serialize = {
	bdid: number,
	boardconfig: string,
	cpid: number,
	platform: string,
};

export type DeviceWithIpsws = DeviceWithIpsws_Serialize | DeviceWithIpsws_Deserialize;

export type DeviceWithIpsws_Deserialize = {
	name: string,
	identifier: string,
	boards: Board_Deserialize[],
	boardconfig: string,
	platform: string,
	cpid: number,
	bdid: number,
	firmwares: IpswFirmware_Deserialize[],
};

export type DeviceWithIpsws_Serialize = {
	name: string,
	identifier: string,
	boards: Board_Serialize[],
	boardconfig: string,
	platform: string,
	cpid: number,
	bdid: number,
	firmwares: IpswFirmware_Serialize[],
};

/**  Môi trường hoạt động của app */
export type DiskEnv = "SSD_ONLY" | "HDD_ONLY" | 
/**  HDD lưu file chính + SSD dùng làm TMP buffer */
"MIXED";

export type DiskEnvironmentInfo = {
	environment: DlEnvironment,
	saveDrive: DriveEnvInfo,
	tmpDrive: DriveEnvInfo | null,
};

export type DlEnvironment = "ssd_save" | "hdd_ssd_tmp" | "hdd_only";

export type DlMediaType = "SSD" | "HDD";

export type DriveEnvInfo = {
	path: string,
	mediaType: DlMediaType,
};

/**  Thông tin chi tiết một ổ đĩa */
export type DriveInfo = {
	/**  Mount point, vd. "C:\\" hoặc "D:\\" */
	mount_point: string,
	/**  Tổng dung lượng (bytes) */
	total_space: number,
	/**  Dung lượng còn trống (bytes) */
	available_space: number,
	/**  Dung lượng đã dùng (bytes) */
	used_space: number,
	media_type: MediaType,
	is_removable: boolean,
	/**  Tên nhãn ổ (nếu có) */
	name: string,
	/**  Hệ thống tập tin, vd. "NTFS", "FAT32" */
	file_system: string,
	/**  Ổ này có chứa Windows không (kiểm tra qua %SystemDrive%) */
	is_system_drive: boolean,
};

/**  Thông tin ổ tối giản dùng cho TMP / save drive trong EnvInfo */
export type DriveRef = {
	path: string,
	media_type: MediaType,
};

/**  Kết quả từ `get_environment_info` */
export type EnvInfo = {
	env: DiskEnv,
	save_drive: DriveRef,
	/**  Chỉ có giá trị khi env == Mixed */
	tmp_drive: DriveRef | null,
};

export type Firmware = {
	identifier: string,
	buildid: string,
	version: string,
	url: string,
	filesize: number,
	releasedate: string,
	uploaddate: string,
	signed: boolean,
	sha1sum?: string | null,
	md5sum?: string | null,
	sha256sum?: string | null,
};

export type FreeSpaceResult = {
	bytes: number,
};

export type IPSWFile = {
	name: string,
	path: string,
	size: number,
};

export type IncompleteTask = {
	id: string,
	firmware: Firmware,
	savePath: string,
	tmpPath: string,
	totalSize: number,
	downloadedBytes: number,
	progress: number | null,
	tmpExists: boolean,
	savedAt: number,
};

export type IpswFirmware = IpswFirmware_Serialize | IpswFirmware_Deserialize;

export type IpswFirmware_Deserialize = {
	sha1sum: string,
	md5sum: string,
	sha256sum: string,
} & BaseFirmware_Deserialize;

export type IpswFirmware_Serialize = {
	sha1sum: string,
	md5sum: string,
	sha256sum: string,
} & BaseFirmware_Serialize;

export type LifecycleError = "NotFound" | "InvalidStatus";

export type LifecycleResult = LifecycleResult_Serialize | LifecycleResult_Deserialize;

export type LifecycleResult_Deserialize = {
	success: boolean,
	error: LifecycleError | null,
};

export type LifecycleResult_Serialize = {
	success: boolean,
	error?: LifecycleError | null,
};

/**  Loại ổ đĩa */
export type MediaType = "SSD" | "HDD" | 
/**  Flash / USB / External / Unknown */
"NONE";

/**
 *  Matches the TS `ModelDataResult` tagged union:
 *    `{ status: "ready", data: DeviceResponse } | { status: "wait" }`
 */
export type ModelDataResult = ModelDataResult_Serialize | ModelDataResult_Deserialize;

/**
 *  Matches the TS `ModelDataResult` tagged union:
 *    `{ status: "ready", data: DeviceResponse } | { status: "wait" }`
 */
export type ModelDataResult_Deserialize = ({ ready: {
	status: "ready",
} & DeviceWithIpsws_Deserialize }) & { wait?: never } | ({ wait: {
	status: "wait",
} }) & { ready?: never };

/**
 *  Matches the TS `ModelDataResult` tagged union:
 *    `{ status: "ready", data: DeviceResponse } | { status: "wait" }`
 */
export type ModelDataResult_Serialize = ({ ready: {
	status: "ready",
} & DeviceWithIpsws_Serialize }) & { wait?: never } | ({ wait: {
	status: "wait",
} }) & { ready?: never };

export type Product = "iphone" | "ipad" | "watch" | "mac" | "realitydevice" | "tv" | "homepod" | "ipod";

export type Task = {
	id: string,
	firmware: Firmware,
	progress: number | null,
	speed: number | null,
	status: TaskStatus,
	eta: number | null,
	error: string | null,
	savePath: string,
	activeConnections: number,
};

export type TaskStatus = "queued" | "downloading" | "paused" | "completed" | "error" | "verifying" | "moving" | "cancelled";

export type UpdateProgress = {
	percent: number | null,
	transferred: string,
	total: string,
};

/**  Mirrors the TS `UpdateStatus` interface. */
export type UpdateStatus = {
	phase: string,
	version: string | null,
	notes: string[] | null,
	progress: UpdateProgress | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

